version: "3.8"

services:
  db:
    image: mariadb
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Customer/sql/script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./Customer
    container_name: fastapi-app
    restart: always
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "mysql://myuser:mypassword@db:3306/mydatabase"
    command: ["/bin/sh", "-c", "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8001"]

volumes:
  db_data:
